name = "imgbed"
compatibility_date = "2024-04-01"
pages_build_output_dir = "./"

# 绑定kv
[[kv_namespaces]]
binding = "img_url"
id = "5f85ee5b6d58470cad9b3b92f66d0e3b"

# R2 绑定
[[r2_buckets]]
binding = "img_r2"
bucket_name = "img-r2-bucket"
